{% set name = "sgkit" %}
{% set version = "0.10.0" %}
{% set sha256 = "f9b5ff1fa75f89c910788857ea13d2f5c4ae0634464a86f3930a325ecc5e6f3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=41.2  # For pkg_resources
    - setuptools_scm
    - pip

  run:
    - python >={{ python_min }}
    # Pinning based on pyproject.toml version in 0.10.0
    - numpy <2.2
    - xarray <2025.03.1
    - dask >=2022.01.0, <=2024.8.0
    - distributed >=2022.01.0, <= 2024.8.0
    - dask-ml
    - scipy
    - zarr >=2.10.0, !=2.11.0,!=2.11.1,!=2.11.2,<3
    - numba
    - typing-extensions
    - fsspec !=2021.6.*
    - scikit-learn
    - pandas
    # bgen support
    - rechunker
    - cbgen >1.0.5
    # plink support
    - partd
    - bed-reader

test:
  requires:
    - python {{ python_min }}
  imports:
    - sgkit

about:
  home: https://pystatgen.github.io/sgkit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical genetics toolkit
  doc_url: https://pystatgen.github.io/sgkit
  dev_url: https://github.com/pystatgen/sgkit

extra:
  recipe-maintainers:
    - jeromekelleher
    - eric-czech
    - tomwhite
