{% set name = "sgkit" %}
{% set version = "0.7.0" %}
{% set sha256 = "b8e482f9b4c757032af667a879bbdbea36b46e1472b3d2bbe4c5e617f1ebe31f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools >=41.2  # For pkg_resources
    - setuptools_scm
    - pip

  run:
    - python >=3.8
    # Pinning based on setup.cfg version in 0.6.0
    - numpy
    - xarray
    - dask >=2022.01.0
    - distributed >=2022.01.0
    - dask-ml
    - scipy
    - zarr >=2.10.0, !=2.11.0,!=2.11.1,!=2.11.2
    - numba
    - typing-extensions
    - fsspec !=2021.6.*
    # bgen support
    - rechunker
    - cbgen
    # plink support
    - partd
    - bed-reader
    # vcf support. We can't directly depend on cyvcf2 here because
    # it's in bioconda.
    #- cyvcf2
    - yarl

test:
  imports:
    - sgkit

about:
  home: https://pystatgen.github.io/sgkit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical genetics toolkit
  doc_url: https://pystatgen.github.io/sgkit
  dev_url: https://github.com/pystatgen/sgkit

extra:
  recipe-maintainers:
    - jeromekelleher
    - eric-czech
    - tomwhite
