{% set name = "sgkit" %}
{% set version = "0.9.0" %}
{% set sha256 = "e08e2610ab3ca41b65bc79c171fb179fa7652129f8b9d74bf81eb15fa39e2f01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - setuptools >=41.2  # For pkg_resources
    - setuptools_scm
    - pip

  run:
    - python >=3.9
    # Pinning based on setup.cfg version in 0.9.0
    - numpy <2
    - xarray
    - dask >=2022.01.0
    - distributed >=2022.01.0
    - dask-ml
    - scipy
    - zarr >=2.10.0, !=2.11.0,!=2.11.1,!=2.11.2,<3
    - numba
    - typing-extensions
    - fsspec !=2021.6.*
    - scikit-learn
    - pandas
    # bgen support
    - rechunker
    - cbgen <1.0.5
    # plink support
    - partd
    - bed-reader
    # vcf support. We can't directly depend on cyvcf2 here because
    # it's in bioconda.
    #- cyvcf2
    - aiohttp
    - requests
    - yarl

test:
  imports:
    - sgkit

about:
  home: https://pystatgen.github.io/sgkit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical genetics toolkit
  doc_url: https://pystatgen.github.io/sgkit
  dev_url: https://github.com/pystatgen/sgkit

extra:
  recipe-maintainers:
    - jeromekelleher
    - eric-czech
    - tomwhite
