{% set name = "sgkit" %}
{% set version = "0.5.0" %}
{% set sha256 = "7a82542849071c585857bfc6caf5e7fc388a850d50886dfd1d5138210adff913" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - setuptools >=41.2  # For pkg_resources
    - setuptools_scm
    - pip

  run:
    - python >=3.7
    # Pinning based on setup.cfg version in 0.4.0
    - numba !=0.54.*
    - dask !=2021.5.1
    - distributed !=2021.5.1
    - fsspec !=2021.6.*
    - numpy
    - xarray
    - dask-ml
    - scipy
    - zarr
    - typing-extensions
    # bgen support
    - rechunker
    - cbgen
    # plink support
    - partd
    - bed-reader
    # vcf support. We can't directly depend on cyvcf2 here because
    # it's in bioconda.
    #- cyvcf2
    - yarl

test:
  imports:
    - sgkit

about:
  home: https://pystatgen.github.io/sgkit
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Statistical genetics toolkit
  doc_url: https://pystatgen.github.io/sgkit
  dev_url: https://github.com/pystatgen/sgkit

extra:
  recipe-maintainers:
    - jeromekelleher
    - eric-czech
    - tomwhite
